name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -r win-x64 -p:PublishSingleFile=true --configuration Release --self-contained true
    - name: Archive Build
      uses: TheDoctor0/zip-release@0.4.1
      with:
        filename: 'latest.zip'
        path: /home/runner/work/bordertale/bordertale/bin/Release/net5.0/win-x64/publish/
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: latest.zip
        path: latest.zip
